// wxcloud/client/src/components/login/index.weapp.vue
<template>
    <View className='<%= pageName %>'>
        <Button @click="getLogin">获取登录云函数</Button>
        <Text>context：{{context}}</Text>
    </View>
</template>

<script>
import Taro from '@tarojs/taro'
import { View, Text, Button } from '@tarojs/components'

export default {
    name: 'login',
    components: {
        View,
        Text,
        Button
    },
    data(){
        return {
            context: {}
        }
    },
    methods: {
        getLogin () {
            Taro.cloud
                .callFunction({
                    name: "login",
                    data: {}
                })
                .then(res => {
                    this.context = JSON.stringify(res.result)
                })
        }
    },
}
</script>

// wxcloud/client/src/components/login/index.weapp.jsx
import { Component{{#if typescript }}, PropsWithChildren{{/if}} } from 'react'
import Taro from '@tarojs/taro'
import { View, Text, Button } from '@tarojs/components'

export default class {{ to_pascal_case pageName }} extends Component{{#if typescript }}<PropsWithChildren>{{/if}} {
  state = {
    context: {}
  }

  componentDidMount() {}

  componentWillUnmount() {}

  componentDidShow() {}

  componentDidHide() {}

  getLogin = () => {
    Taro.cloud
      .callFunction({
        name: "login",
        data: {}
      })
      .then(res => {
        this.setState({
          context: res.result
        })
      })
  }

  render() {
    return (
      <View className='{{ pageName }}'>
        <Button onClick={this.getLogin}>获取登录云函数</Button>
        <Text>context：{JSON.stringify(this.state.context)}</Text>
      </View>
    )
  }
}
