// wxplugin/src/pages/index/index.vue
<template>
  <view class="{{ pageName }}">
    <text>\{{msg}}</text>
    <avatar />
    <navigator url='plugin://myPlugin/list'>
      Go to pages/list!
    </navigator>
  </view>
</template>

<script>
{{#if (eq framework 'Vue3') }}
import { ref } from 'vue'
{{/if}}
import './index.{{ cssExt }}'

export default {
{{#if (eq framework 'Vue') }}
  data () {
    return {
      msg: 'Hello world!'
    }
  }
{{/if}}
{{#if (eq framework 'Vue3') }}
  setup () {
    const msg = ref('Hello world')
    return {
      msg
    }
  }
{{/if}}
}
</script>

// wxplugin/src/pages/index/index.jsx
<%if (framework === 'react') {-%>
import React, { Component } from 'react'
<%} else if (framework === 'nerv') { -%>
import Nerv, { Component } from 'nervjs'
<%}-%>
import { View, Text, Navigator } from '@tarojs/components'
import './index.<%= cssExt %>'

const myPluginInterface = Taro.requirePlugin('myPlugin')

export default class <%= _.capitalize(pageName) %> extends Component {
  componentDidMount () {
    myPluginInterface.sayHello()
    const answer = myPluginInterface.answer
    console.log('answer: ', answer)
  }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  render () {
    return (
      <View className='<%= pageName %>'>
        <Text>Hello world!</Text>
        <avatar />
        <Navigator url='plugin://myPlugin/list'>
          Go to pages/list!
        </Navigator>
      </View>
    )
  }
}
