// default-youshu/src/pages/index/index.vue
<template>
  <view class="{{ pageName }}">
    <text>{{ msg }}</text>
  </view>
</template>

<script>
{{#if (eq framework 'Vue3') }}
import { ref } from 'vue'
{{/if}}
import './index.{{ cssExt }}'

export default {
{{#if (eq framework 'Vue') }}
  data () {
    return {
      msg: 'Hello world!'
    }
  }
{{/if}}
{{#if (eq framework 'Vue3') }}
  setup () {
    const msg = ref('Hello world')
    return {
      msg
    }
  }
{{/if}}
}
</script>

// react-native/src/pages/index/index.jsx
import { Component } from 'react'
import { View, Text } from '@tarojs/components'
import './index.<%= cssExt %>'

export default class <%= _.capitalize(pageName) %> extends Component {

  componentDidMount () { }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  render () {
    return (
      <View className='<%= pageName %>'>
        <Text>Hello world!</Text>
      </View>
    )
  }
}
