// wxcloud/client/src/pages/index/index.vue
<template>
  <view className='<%= pageName %>'>
    <Login />
  </view>
</template>

<script>
import { View, Text } from '@tarojs/components'
import './<%= pageName %>.<%= cssExt %>'
import Login from '../../components/login/index'

export default {
  name: 'Index',
  components: {
    Login,
    View,
    Text
  }
}
</script>

// react-native/src/pages/index/index.jsx
import { Component } from 'react'
import { View, Text } from '@tarojs/components'
import './index.<%= cssExt %>'

export default class <%= _.capitalize(pageName) %> extends Component {

  componentDidMount () { }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  render () {
    return (
      <View className='<%= pageName %>'>
        <Text>Hello world!</Text>
      </View>
    )
  }
}
