// taro-ui/src/pages/index/index.vue
<template>
  <view class="{{ pageName }}">
    <text>\{{ msg }}</text>
    <AtButton
      type="primary"
      :on-click="handleClick"
    >
      I need Taro UI
    </AtButton>
  </view>
</template>

<script>
{{#if (eq framework "Vue3") }}
import { ref } from 'vue'
{{/if}}
import { AtButton } from 'taro-ui-vue'
export default {
  {{#if (eq framework "Vue") }}
  data () {
    return {
      msg: 'Hello world!'
    }
  }
  {{/if}}
  {{#if (eq framework "Vue3") }}
  setup () {
    const msg = ref('Hello world')
    return {
      msg
    }
  }
  {{/if}}
}
</script>

// taro-ui/src/pages/index/index.jsx
<%if (framework === 'react') {-%>
import React, { Component } from 'react'
<%} else if (framework === 'nerv') { -%>
import Nerv, { Component } from 'nervjs'
<%}-%>
import { View, Text } from '@tarojs/components'
import './<%= pageName %>.<%= cssExt %>
import { AtButton } from 'taro-ui'

export default class <%= _.capitalize(pageName) %> extends Component {

  componentWillMount () { }

  componentDidMount () { }

  componentWillUnmount () { }

  componentDidShow () { }

  componentDidHide () { }

  render () {
    return (
      <View className='<%= pageName %>'>
        <Text>Hello world!</Text>
        <AtButton type='primary'>I need Taro UI</AtButton>
        <Text>Taro UI 支持 Vue 了吗？</Text>
        <AtButton type='primary' circle={true}>支持</AtButton>
        <Text>共建？</Text>
        <AtButton type='secondary' circle={true}>来</AtButton>
      </View>
    )
  }
}
