// wxplugin/src/plugin/components/listItem/listItem.vue
<template>
  <view>
    <view>name: \{{name}}</view>
    <view>value: \{{value}}</view>
  </view>
</template>

<script>
{{#if (eq framework 'Vue3') }}
import { ref } from 'vue'
{{/if}}
import './listItem.{{ cssExt }}'

export default {
{{#if (eq framework 'Vue') }}
  props: ['name', 'value']
{{/if}}
{{#if (eq framework 'Vue3') }}
  props: ['name', 'value']
{{/if}}
}
</script>

// wxplugin/src/plugin/components/listItem/listItem.jsx
import Component from 'react'
import { View } from '@tarojs/components'
import './listItem.{{ cssExt }}'

{{#if typescript }}
interface IListItem {
  name: string,
  value: string
}
{{/if}}

export default class ListItem extends Component{{#if typescript }}<IListItem, any>{{/if}} {
  render () {
    const { name, value } = this.props
    return (
      <View>
        <View>name: {name}</View>
        <View>value: {value}</View>
      </View>
    )
  }
}
